### PR TITLE
Update events

### PR DESCRIPTION
**Pull request by pwalczysko**
Updating events:

1. Add EastBio
2. Put into past tense and add Resources:
   - CBI Montreal
   - CRG Barcelona

cc @jburel

### CODE REVIEW

**Comment by pwalczysko** [comment]
Failure: Plenty of the license links which we are using are indeed 404-ing on the gnu website, e.g. https://www.gnu.org/copyleft/gpl.html - any idea how to replace please @jburel @joshmoore ?

**Comment by joshmoore** [comment]
Even internal links on the gnu.org webpage are broken! Perhaps it was a recent change. Looks like they moved to versioned URLs like https://www.gnu.org/licenses/gpl-3.0.html

**Comment by pwalczysko** [comment]
@joshmoore @jburel and now it is green. Just a simple rerun... Maybe we merge quickly if you are happy please ?

**Comment by pwalczysko** [comment]
Tagging done. To solve the ``mystery`` here as well: When clicking on    https://www.gnu.org/copyleft/gpl.html     I am redirected to https://www.gnu.org/licenses/gpl-3.0.html - so I guess they did they redirects homework o/n

**Pull request merged**
