### PR TITLE
Add speaker

### PR DESCRIPTION
**Pull request by lunson**
Edit from Jason: add Sebastien Tosi as a speaker

### CODE REVIEW

**Comment by pwalczysko** [comment]
Builds well and looks good on https://snoopycrimecop.github.io/www.openmicroscopy.org/

Ready to merge fmpov. 
There could be a release of www pages on Monday ?

**Comment by pwalczysko** [comment]
@lunson Please note that the registration opened just now https://forum.image.sc/t/ome-community-meeting-may-26-28-dundee/32924/4

**Comment by lunson** [comment]
@pwalczysko I'll add registration and another edit from Jason to this PR. Thanks.

**Comment by pwalczysko** [comment]
Builds well and looks good on https://snoopycrimecop.github.io/www.openmicroscopy.org/.
If you @lunson and @jrswedlow are happy, I can merge and deploy www site with this tomorrow.

**Comment by lunson** [comment]
@pwalczysko Jason asked me to remove the registration button from Home page only. This is good to go live now. Thanks!

**Comment by pwalczysko** [comment]
@lunson and @jrswedlow understood and looks good and according to what you indicated on https://snoopycrimecop.github.io/www.openmicroscopy.org/

**Comment by pwalczysko** [comment]
Merging to deploy

**Pull request merged**
