### PR TITLE
add URL to config

### PR DESCRIPTION
**Pull request by lunson**
@joshmoore Here I go again. Crossing fingers. No rush.

### CODE REVIEW

**Comment by chris-allan** [comment]
The intermediate artifacts aren't going anywhere after the Travis build unfortunately so it's difficult to be 100% sure but when run locally with the `jekyll/builder` Docker container this seems to give us what we want:

```
...
<url>
<loc>https://www.openmicroscopy.org/www.openmicroscopy.org/2014/02/25/omero-bio-formats-5-0-0.html</loc>
<lastmod>2014-02-25T00:00:00-06:00</lastmod>
</url>
...
```

This is despite https://snoopycrimecop.github.io/www.openmicroscopy.org/sitemap.xml definitely not being correct.

/cc @joshmoore, @manics

**Comment by chris-allan** [comment]
Scratch that. Definitely not correct. There's a `www.openmicroscopy.org` prefix to all the URLs in the sitemap.

**Comment by chris-allan** [comment]
@lunson: Can you set `url: "https://www.openmicroscopy.org"` in `_prod.yml` and `https://snoopycrimecop.github.io/www.openmicroscopy.org` in `_config.yml` and push?

We'll see if that gives us what we need in both situations.

@joshmoore: Do we have other deployment situations where we need to make sure things correctly resolve?

**Comment by joshmoore** [comment]
Those are the only two that I can think of offhand.

**Comment by chris-allan** [comment]
Much better:

```
...
<url>
<loc>https://www.openmicroscopy.org/2014/02/25/omero-bio-formats-5-0-0.html</loc>
<lastmod>2014-02-25T00:00:00-06:00</lastmod>
</url>
...
```

**Comment by chris-allan** [comment]
Sorry @lunson, one more pass. In `_config.yml`, `url: "https://snoopycrimecop.github.io"` please.

**Comment by chris-allan** [comment]
Looking good for https://snoopycrimecop.github.io/www.openmicroscopy.org/ as well:

```
...
<url>
<loc>
https://snoopycrimecop.github.io/www.openmicroscopy.org/2014/02/25/omero-bio-formats-5-0-0.html
</loc>
<lastmod>2014-02-25T00:00:00+00:00</lastmod>
</url>
...
```

**Comment by joshmoore** [comment]
@jburel : leaving this & its deployment to you.

**Comment by joshmoore** [comment]
Rolling this into the community meeting update.

**Pull request merged**
