### PR TITLE
Update events

### PR DESCRIPTION
**Pull request by pwalczysko**
Adding EMBL-EBI and ELMI workshops.

cc @jburel

### CODE REVIEW

**Comment by jburel** [comment]
Do you also want to add the upcoming one in Panama?

**Comment by pwalczysko** [comment]
> Do you also want to add the upcoming one in Panama?

Added in https://github.com/ome/www.openmicroscopy.org/pull/712/commits/81ce784c0928a91a71f4a2cefc2c122679fa83bd

**Comment by pwalczysko** [comment]
built at https://snoopycrimecop.github.io/www.openmicroscopy.org/events/

**Comment by pwalczysko** [comment]
Happy for me to merge ?

**Pull request merged**
