### PR TITLE
Change Media Cybernetics as per request

### PR DESCRIPTION
**Pull request by pwalczysko**
Changing the branding of Media... as per recent communication.

cc @dgault @jrswedlow

### CODE REVIEW

**Comment by pwalczysko** [comment]
Somehow this PR is not showing on snoopy https://snoopycrimecop.github.io/www.openmicroscopy.org/commercial-partners/ although it was included in https://merge-ci.openmicroscopy.org/jenkins/job/WEBSITE-push/1027/console - any ideas @jburel please ?

**Comment by jburel** [comment]
It must have been a caching issue 
I can see the change see 
Screenshot 2023-01-10 at 20 24 30

**Comment by pwalczysko** [comment]
@jburel ah, thanks, great, sorry, I was wrong-footed by thinking about the CI work.

**Comment by pwalczysko** [comment]
Does this look good to you @dgault please ?

**Pull request merged**
