### PR TITLE
OME2022: deactivate banner and swap OME2021 links

### PR DESCRIPTION
**Pull request by joshmoore**
Updated/fixed a few different locations:

* Dropped the current release banner

* Updated the footer
Screen Shot 2022-10-24 at 08 21 31

* Updated the navigation menu
Screen Shot 2022-10-24 at 08 21 43

### CODE REVIEW

**Comment by joshmoore** [comment]
I note that the URL style changed from last year:

```
  internally linking to /events/ome-community-meeting-2022/, which does not exist
```

was there any discussion around this or could I unify the URLs and redirect from:

```
/events/ome-community-meeting-november-2022.html
```

cc: @jburel @pwalczysko

**Comment by pwalczysko** [comment]
> could I unify the URLs and redirect from:

No discussion afaik. So yes please, if you can fmpov

**Comment by jburel** [comment]
I think @pwalczysko used ``.html`` because we ended up with only one file instead of the various generated pages we had last year.

**Comment by joshmoore** [comment]
Bit confused why this is failing since the 404s are in the file I've _moved_!

```
* At /site/events/ome-community-meeting-november-2022.html:5:

  External link https://www.openmicroscopy.org/events/ome-community-meeting-2022/ failed (status code 404)

* At /site/events/ome-community-meeting-november-2022.html:10:

  External link https://www.openmicroscopy.org/events/ome-community-meeting-2022/ failed (status code 404)
```
It might be that this will correct itself on publication.

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
