### PR TITLE
OMERO.server is now v5.6.3 and OMERO.insight is now v5.5.13.

### PR DESCRIPTION
**Pull request by mtbc**
Diff should make plain.

### CODE REVIEW

**Comment by pwalczysko** [comment]
Travis fails with (possibly) not finidng the doc ?

```
External link https://docs.openmicroscopy.org/omero/5.6.3/developers/index.html failed: 403 No error[0m
...
```

**Comment by mtbc** [comment]
Yes, the docs aren't publicly released yet. If you visit the URI manually from within sshuttle/VPN you should find the page is there but Travis can't see that.

**Comment by pwalczysko** [comment]
From the ci job console output it seems that this PR has been merged

```
Merged PRs:
  - PR 286 sbesson 'Migrate generated schemas pages under static website'
  - PR 403 joshmoore 'Community meeting updates'
  - PR 406 mtbc 'Announce release of OMERO.server 5.6.3.'
  - PR 408 mtbc 'OMERO.server is now v5.6.3 and OMERO.insight is now v5.5.13.'
```

But https://snoopycrimecop.github.io/www.openmicroscopy.org/omero/downloads/ does not show the client and server versions you mention, @mtbc ?

**Comment by pwalczysko** [comment]
@mtbc oh, sorry, ignore https://github.com/ome/www.openmicroscopy.org/pull/408#issuecomment-701275643 - there was some time delay, after which it fixed itself

Screen Shot 2020-09-30 at 10 31 07
Screen Shot 2020-09-30 at 10 30 59

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
