### PR TITLE
Convert custom YAML contributor data files to use schema.org compliant JSON

### PR DESCRIPTION
**Pull request by sbesson**
This proposes to converts the  contributors files currently stored in a custom YML format into three separate JSON files following schema.org:
-  a list of all OME contributors using [Person](https://schema.org/Person)
- one [SoftwareApplication](https://schema.org/SoftwareApplication) file for each software referring to the the contributors via @id

One of the drivers beyond the `contributors.json` file was also to have a single place listing all third-party contributors alongside the status of the CLA. Initial thought was to add a field in the `Person` element but I have not found a relevant ontology term. Other options would be: two lists/graphs within the contributors.json or a separate `cla.json` which would refer to individual `@id`.

The files were generated using the script below and some cleanup is required (duplicates...) but initially opening for a round of feedback on this approach.

```py
#! Converter

import yaml
import json
CONTRIBUTORS_URL = "https://www.openmicroscopy.org/contributors"

contributors = {}
with open('_data/contributors/omero.yml', 'r', encoding='utf-8') as f:
    contributors["omero"] = yaml.safe_load(f)

with open('_data/contributors/bio-formats.yaml', 'r', encoding='utf-8') as f:
    contributors["bio-formats"] = yaml.safe_load(f)

contributors_dict = {
    "@context": "https://schema.org",
    "@graph": []
}

for software in contributors:
    software_dict = {
        "@context": "https://schema.org",
        "@type": "SoftwareApplication",
        "contributor": []
    }
    if software == "omero":
        software_dict["name"] = "OMERO"
    else:
        software_dict["name"] = "Bio-Formats"
    software_dict["url"] = "https://www.openmicroscopy.org/%s" % software

    for c in contributors[software]:
        contributor= {
            "@type": "Person",
            "givenName": c["fullname"].split(" ")[0],
            "familyName": " ".join(c["fullname"].split(" ")[1:]),
            "affiliation": []
        }
        for affiliation in c.get("affiliations", []):
            contributor["affiliation"].append({
                "@type": "Organization",
                "name": affiliation["name"],
                "url": affiliation["url"]
            })
        if c.get("githubname", None):
            contributor["sameAs"] = "https://github.com/%s" % c["githubname"]
            c_id = c["githubname"]
        else:
            c_id = c["fullname"].replace(" ", "")
        contributor["@id"] = "%s#%s" % (CONTRIBUTORS_URL, c_id)
        contributors_dict["@graph"].append(contributor)
        software_dict["contributor"].append({
            "@id": contributor["@id"]
        })
    with open("_data/%s.json" % software, 'w', encoding="utf8") as f:
        f.write(json.dumps(
            software_dict, sort_keys=True, indent=4, ensure_ascii=False))

with open("_data/contributors.json", "w", encoding="utf8") as f:
    f.write(json.dumps(
        contributors_dict, sort_keys=True, indent=4, ensure_ascii=False))

```

### CODE REVIEW

**Comment by joshmoore** [comment]
`contributors.json` format looks generally good. Guess I would have thought something simpler might be possible for the references in `bioformats.json`.

**Comment by sbesson** [comment]
> Guess I would have thought something simpler might be possible for the references in bioformats.json.

Are your referring to simplifying the individual `@id` or simplifying the list type? For the latter based on the [contributor](https://schema.org/contributor) schem, I think an alternative option could be to define a group of people as an `Organization` e.g. `Bio-Formats contributors` managed in `contributors.json`, and refer to this rather than individuals from `bio-formats.json` ?

**Comment by joshmoore** [comment]
More referring to the reference. i.e. would just the URL suffice? or do you need the object with a `@type`?

**Comment by sbesson** [comment]
Cheers. Just tested the removal of `@type` using https://validator.schema.org/ and the nodes are simply inferred as https://schema.org/Thing which I think is fine

**Comment by sbesson** [comment]
The latest version is now deployed at https://snoopycrimecop.github.io/www.openmicroscopy.org/contributors/ (to be compared to https://www.openmicroscopy.org/contributors/).

Also see https://validator.schema.org/#url=https%3A%2F%2Fsnoopycrimecop.github.io%2Fwww.openmicroscopy.org%2Fomero, https://validator.schema.org/#url=https%3A%2F%2Fsnoopycrimecop.github.io%2Fwww.openmicroscopy.org%2Fcontributors and https://validator.schema.org/#url=https%3A%2F%2Fsnoopycrimecop.github.io%2Fwww.openmicroscopy.org%2Fbio-formats

**Comment by joshmoore** [comment]
Changes generally look good. (1) I didn't look for any individual deletion. I'm sure you wouldn't allow that :wink: (2) Still interested in getting the full JSON-LD into the HTML but that could probably best use a plugin, etc. :+1:

**Comment by sbesson** [comment]
(1) no deletion I am aware of, the script mentioned in the description should ensure every contributor listed has been converted into the new layout and d670547f49db9f1501572f473f7c6c677bf84fdd contains the only modifications (mostly duplication removal)

(2) by getting the full JSON-LD I assume you mean joining the two JSON documents into a single JSON-LD available from the Website with the full metadata? Definitely interested to read more about the best practices here in general.

I am still looking into ways to encode the CLA into this representation and minimize the number of places to maintain. This raises one process question: would we add a contributor to `contributors.json` as soon as we receive a CLA, primarily for management reasons? The process of acknowledging contributions for a given project could still be  reviewed later at release time but that would guarantee the identifier of every new contributor would already have been defined. /cc @jburel @dgault

**Comment by jburel** [comment]
Minor suggestions to fix typo then this can be merged

**Comment by sbesson** [comment]
> Minor suggestions to fix typo then this can be merged

where are these?

**Comment by jburel** [comment]
Oops  I forgot to press the submit button

**Pull request merged**
