### PR TITLE
Switch to GitHub actions

### PR DESCRIPTION
**Pull request by sbesson**
As the VMs are getting migrated away from travis-ci.org, the PR validation times become unusable. Like for the rest of the OME repositories, this is now switching the CI infrastructure to GitHub worklows using the same workflow as the one used in https://github.com/IDR/idr.openmicroscopy.org/pull/113

- the build & linkcheck steps are being moved to a `build.sh` script
- the workflow should upload an artifact for each PR which can be inspected for quick testing

### CODE REVIEW

**Comment by sbesson** [comment]
@pwalczysko  see https://github.com/sbesson/www.openmicroscopy.org/actions/runs/382926190 for an example of run including the downloadable website bundle.

**Comment by pwalczysko** [comment]
Maybe a question about the checking process of the website bundle you are pointing me to in https://github.com/ome/www.openmicroscopy.org/pull/425#issuecomment-733604531 - I downloaded that bundle and did the following commands as specified beow, but the browser seems to be missing some css or somesuch (I simply opened the index.html). Could you please expand on how to inspect the bundle ?

```
unzip www.openmicroscopy.org.tar.gz.zip 
Archive:  www.openmicroscopy.org.tar.gz.zip
  inflating: www.openmicroscopy.org.tar.gz  
...
tar xzf www.openmicroscopy.org.tar.gz
(base) pwalczysko@ls31618~/www-testing$ ls
2014					events
2015					explore
2016					fonts
2017					img
2018					index.html
2019					js
2020					licensing
404.html				minutes
CONTRIBUTING.md				news
LICENSE					ome-files
README.md				omero
about					on-the-web
announcements				products
artwork					redirects.json
assets					robots.txt
bio-formats				security
build.sh				site-map
careers					sitemap.xml
citing-ome				support
commercial-partners			teams
contributors				training
css					www.openmicroscopy.org.tar.gz
docker_startup.sh			www.openmicroscopy.org.tar.gz.zip
docs
(base) pwalczysko@ls31618~/www-testing$ open index.html 
```

**Comment by sbesson** [comment]
Sorry, I assumed that it would just work when opening the index but indeed the CSS is broken by default. This is unrelated to this change all release bundles exhibit the same behavior.

I was hoping to have a per-PR review mechanism at the same time but it seems for the short-term we will need to keep using the staging deployment of https://snoopycrimecop.github.io/www.openmicroscopy.org/ to deploy contributions.

**Comment by pwalczysko** [comment]
> I was hoping to have a per-PR review mechanism at the same time 

Yes, we have snoopy and for single PRs, I am using the https://github.com/ome/www.openmicroscopy.org/blob/master/docker_startup.sh built locally, so I am not too worried there.

For the testing of this PR, maybe I could deploy the artifact in https://github.com/sbesson/www.openmicroscopy.org/actions/runs/382926190 using the deployment workflow on ``ome-www-dev`` ? Something like 
``ansible-playbook -K /path/to/www-static.yml -i path/to/ansible/inventory/staging-hosts -l ome-www-dev.openmicroscopy.org`` ?
This is actually also an interesting question, as travis was producing the release artifacts up till now for deployment - there was a checksum which needed to be changed in the deployment ansible playbook. How does this workflow change now ?

**Comment by sbesson** [comment]
:+1: for testing a real deployment of the artifact produced by this workflow as a validation. My expectation is that it should work out of the box.

Regarding checksum, this is currently created during the second part of the GitHub workflow which is only executed on tags. If you think it is valuable, it should be easy enough to generate as part of the first job in the workflow and upload as an artifact. Note that the role syntax allows you to omit the checksum variable or set it as empty which should ignore the check.

**Comment by pwalczysko** [comment]
Deployed successfully on ``ome-www-dev`` the ``2020.11.25`` release from https://github.com/sbesson/www.openmicroscopy.org/releases  

All looks good. Ready to merge fmpov

**Review by pwalczysko — APPROVED** [review]

**Pull request merged**
