### PR TITLE
Update banner to mention imminent OMERO 5.6.1 release.

### PR DESCRIPTION
**Pull request by mtbc**
On release can update banner to link to `{{ site.baseurl }}/2020/03/25/omero-5-6-1.html`.

### CODE REVIEW

**Comment by joshmoore** [comment]
A heads up to @lunson that her CSS could be in danger :wink:

**Comment by lunson** [comment]
@joshmoore No worries. There's a lot of red on the website so it works @manics!

**Comment by sbesson** [comment]
Screen Shot 2020-03-18 at 09 28 00


Everyone okay with having this deployed live asap?

**Comment by joshmoore** [comment]
WFM

**Comment by sbesson** [comment]
https://www.openmicroscopy.org/ now updated with the new security announcement

**Pull request merged**
