### PR TITLE
OME 2022

### PR DESCRIPTION
**Pull request by pwalczysko**
In prep of UnMeeting OME 2022

cc @jburel 

built https://snoopycrimecop.github.io/www.openmicroscopy.org/events/

### CODE REVIEW

**Comment by jburel** [comment]
You have a typo in the event name
https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ome-community-meeting-november-2022.html leads to a 404

**Comment by jburel** [comment]
@pwalczysko could you also update the front page to point the 2022 event

**Comment by pwalczysko** [comment]
> @pwalczysko could you also update the front page to point the 2022 event

Sure, I have to figure out how, also, I guess the formatting on the new event will be iffy.

**Comment by pwalczysko** [comment]
Thanks, Lgtm now, also see https://openmicroscopy.slack.com/archives/C0K5EED3R/p1666352249695589 @jburel . If fine for you too, I can push a tag after lunch

**Review by jburel — APPROVED** [review]

**Comment by jburel** [comment]
Thanks @pwalczysko

**Comment by will-moore** [comment]
For the record, command for building locally, pinning version:

```
docker pull jekyll/builder@sha256:538c62d949f3effe176d0b8719ed12c2be1c38e482b1f766b06c1406ac943728
docker run -it --rm -p 4000:4000 -v $PWD:/srv/jekyll jekyll/builder@sha256:538c62d949f3effe176d0b8719ed12c2be1c38e482b1f766b06c1406ac943728 jekyll server -w
```

**Pull request merged**
