### PR TITLE
Add video placeholders

### PR DESCRIPTION
**Pull request by lunson**
--exclude

This replaces https://github.com/ome/www.openmicroscopy.org/pull/361 (I got stuck on a merge conflict and had to cherry-pick, sorry) and includes what is live on the website as of this message.

Feel free to use once real videos are ready.

### CODE REVIEW

**Comment by pwalczysko** [comment]
@lunson sorry, still conflicts are reported here

**Comment by lunson** [comment]
@pwalczysko Hopefully this is all okay now. I'm only here for a few more hours so speak now or forever hold your peace :wink:

**Comment by pwalczysko** [comment]
@lunson yes, and thank you very much. @will-moore wanted to have a look on how to re-organize the page, thanks a lot for all

**Comment by lunson** [comment]
@will-moore ^ Don't forget to add Paina's affiliation! That's it from me. Bye now!

**Comment by will-moore** [comment]
Yes, I did that in https://github.com/ome/www.openmicroscopy.org/pull/370/commits/8d7cd3df13b1fdb5a9c248560309fe78e712bf55 thanks!

**Comment by pwalczysko** [comment]
@will-moore what course of action would you suggest on this PR ? Is it fully redundant now ? Maybe close ?

**Comment by will-moore** [comment]
Yes, can close now thanks.

**Pull request closed without merging**
