### PR TITLE
Update day 1 IDR entry to point at the recorded video

### PR DESCRIPTION
**Pull request by sbesson**
- also update the thumbnail to use a smaller size

### CODE REVIEW

**Comment by pwalczysko** [comment]
Cannot build this repo on ci.

```
2020-05-22 20:49:26,386 [      scc.gh] DEBUG github.__len__
2020-05-22 20:49:28,072 [    scc.repo] ERROR Failed to find openmicroscopy/www.openmicroscopy.org
Traceback (most recent call last):
  File "/home/hudson/virtualenv/lib/python2.6/site-packages/scc/main.py", line 84, in entry_point
    (UpdateSubmodules.NAME, UpdateSubmodules),
  File "/home/hudson/virtualenv/lib/python2.6/site-packages/yaclifw/framework.py", line 188, in main
    ns.func(ns)
  File "/home/hudson/virtualenv/lib/python2.6/site-packages/scc/git.py", line 3211, in __call__
    self.init_main_repo
```

but the site is fine. Re-treid several times, but random errors repeat.

**Comment by pwalczysko** [comment]
The problem above with the build sorted itself out (hard to say how).

But now, the Day 1 page of the programme on snoopy is not happy https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ome-community-meeting-2020/day1/
Whereas the Day 2 is still going strong. I suspect that might be connected to this PR ?

**Comment by pwalczysko** [comment]
I built this PR locally, and also there, the DAy1 page is bust, no content, jsut header with no css.

**Comment by pwalczysko** [comment]
I excluded this PR by adding 
--exclude and re-run the build. Now, on snoopy, the Day 1 is back in shape.

Leaving this PR as excluded, untill this is clarified.

**Comment by sbesson** [comment]
Thanks for the feedback @pwalczysko. Updated and deployed at https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ome-community-meeting-2020/day1/

**Comment by will-moore** [comment]
Looks good.
Also just deployed https://github.com/ome/www.openmicroscopy.org/pull/378 there too.

**Comment by pwalczysko** [comment]
Thanks all, merged as per email.

**Pull request merged**
