### PR TITLE
Add links to old support forums

### PR DESCRIPTION
**Pull request by manics**
Screen Shot 2019-06-13 at 11 24 33-fullpage
See https://forum.image.sc/t/migration-of-ome-phpbb-forums-and-mailing-lists/25817/5?u=manics

### CODE REVIEW

**Comment by joshmoore** [comment]
Asked @lunson whether or not there was a style for a footnote, but there's not one at the moment. I'd say let's get this in ASAP, and if it looks like we're going to have to keep the old resources around for a while, we'll look into updating the formatting.

@manics : you ok to deploy?

**Comment by manics** [comment]
Can do, once https://github.com/ome/www.openmicroscopy.org/pull/269 is agreed

**Comment by joshmoore** [comment]
Agreed as far as I'm concerned. Leave you to get further sign-offs.

**Comment by sbesson** [comment]
Now deployed live at https://www.openmicroscopy.org/support/

**Pull request merged**
