### PR TITLE
Fix location and organizer as requested

### PR DESCRIPTION
**Pull request by pwalczysko**
As per organizers request

cc @jburel @joshmoore 

Review can be done locally by using the command https://github.com/ome/www.openmicroscopy.org/blob/master/docker_startup.sh

### CODE REVIEW

**Comment by pwalczysko** [comment]
There is also a CI build of this, but I just cannot find it cc @joshmoore @jburel

**Comment by jburel** [comment]
@pwalczysko https://ci.openmicroscopy.org/view/Mgmt/job/WWW-merge I think that the job you were looking for

**Comment by will-moore** [comment]
But I don't see the staged build for that job?

**Comment by will-moore** [comment]
Built locally with docker - looks good, links work etc. 
Good to merge

**Comment by pwalczysko** [comment]
@jburel @joshmoore could we merge and deploy please ?

**Comment by jburel** [comment]
done prod and staging updated

**Pull request merged**
