### PR TITLE
Change hero image to market OME Community Meeting

### PR DESCRIPTION
**Pull request by lunson**
(priority to be determined by you guys)

This is a proposed design for the hero image of the home page to market the upcoming Users Meeting and to visually convey the idea that the meeting this year is entirely remote. 

**Note:** All text and all links are placeholders only.

_If someone could please ping me when the program is ready or close to ready (even a draft will do), I can work it into the website and create a template for the team to work with. It would be **ideal** to have a headshot included for any speakers and would be preferred over organization logos, but if we can't make that happen then I can come up with a different design that works. Thanks._

### CODE REVIEW

**Comment by lunson** [comment]
Per the team meeting earlier today, I removed anything linking to pending items and instead linked to what's currently live. 

Please let me know of any changes you'd suggest. Thanks!

**Comment by manics** [comment]
image


The body text looks a bit large, but that might be OK once the program is filled in so I think it's fine for now:
image

**Comment by pwalczysko** [comment]
@lunson You might consider merging https://github.com/lunson/www.openmicroscopy.org/pull/6 - removal of the two stars on the Paris and Munsingen events.

**Comment by jrswedlow** [comment]
Looks good @lunson-- thx!

**Comment by sbesson** [comment]
@pwalczysko leaving you to sign off on Liza's last commits and I will deploy

**Comment by pwalczysko** [comment]
Screen Shot 2020-04-14 at 09 29 20
 looks good

**Comment by pwalczysko** [comment]
Happy, merging (led by @sbesson )

**Comment by lunson** [comment]
Hmmm... anyone else _not_ seeing the changes live?

**Comment by pwalczysko** [comment]
@lunson The changes are not live yet. What you see is expected.

**Comment by sbesson** [comment]
https://www.openmicroscopy.org/ has now been updated by @pwalczysko with these changes

**Pull request merged**
