### PR TITLE
Add real videos

### PR DESCRIPTION
**Pull request by will-moore**
Adds to @pwalczysko #372.

Uses a ```<video>``` tag with ```poster``` for placeholder.

NB: When we add a video, we now need to add a placeholder image and set the ```vid_poster1``` to point to it in order for the video to show up on the page.

See https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ome-community-meeting-2020/day1/ and day2

### CODE REVIEW

**Comment by pwalczysko** [comment]
Looks good to me on https://snoopycrimecop.github.io/www.openmicroscopy.org/events/ome-community-meeting-2020/day2/ . See what @jrswedlow thinks, thanks @will-moore

**Comment by will-moore** [comment]
One thought - do we want the videos to play in-line when they are so small? Maybe they should just be links to the full-sized video?

**Comment by pwalczysko** [comment]
> One thought - do we want the videos to play in-line when they are so small? Maybe they should just be links to the full-sized video?

But you can maximize your screen once the play starts. See what @jrswedlow thinks.

**Comment by manics** [comment]
Ideally people could watch it in a window without going full screen so they can still see their other applications

**Comment by pwalczysko** [comment]
Practice talks are removed, as verified via snoopy.
@jrswedlow okayed this, merging for release.

**Pull request merged**
