### PR TITLE
Update events, add ome-community-meeting

### PR DESCRIPTION
**Pull request by pwalczysko**
Updating events, adding the OME community meeting.

cc @jburel @jrswedlow @joshmoore @will-moore @dominikl

### CODE REVIEW

**Comment by pwalczysko** [comment]
You can build this PR locally with https://github.com/ome/www.openmicroscopy.org/blob/master/docker_startup.sh

@mtbc There was also a magical snoopy link somewhere, where all is built, would you know where please ?

**Comment by mtbc** [comment]
Trigger [WWW-merge](https://ci.openmicroscopy.org/job/WWW-merge/) (happens nightly anyway) and the pages soon appear at https://snoopycrimecop.github.io/www.openmicroscopy.org/.

**Comment by mtbc** [comment]
Just a thought: I wonder if some kind of "all are welcome" or something is useful, making it clear that the "OME community" aren't just the consortium members or whatever.

**Comment by mtbc** [comment]
Maybe this should be on "announcements"? It's far more than a workshop.

**Comment by joshmoore** [comment]
> Maybe this should be on "announcements"? It's far more than a workshop.

All the other user meetings are under events. A filter of some kind might be nice long term though.

> I wonder if some kind of "all are welcome" or something is useful, making it clear that the "OME community" aren't just the consortium members or whatever.

:+1:

though I could see getting this PR out ASAP and then we can add to it as we have ideas, etc.

**Comment by mtbc** [comment]
Ah, it is under "events" indeed, I got to it by "Upcoming Workshops" which confused me.

**Comment by pwalczysko** [comment]
> I got to it by "Upcoming Workshops" which confused me.

Long history. And would need a "political" discussion within the team - the question is : real estate at the "first coming to op...py.org website" - what should catch your attention first ?

**Comment by pwalczysko** [comment]
Seems  that "merge and deploy now" opinion is winning, see https://openmicroscopy.slack.com/archives/C0K5EED3R/p1582277689437400

**Comment by pwalczysko** [comment]
See also https://openmicroscopy.slack.com/archives/C0K5EED3R/p1582277888441100

**Comment by will-moore** [comment]
LGTM 👍

**Comment by joshmoore** [comment]
Thanks all. Releasing to production. Looking forward to more PRs: marketing helps us all :wink:

**Pull request merged**
