### PR TITLE
Add OMERO to licensing

### PR DESCRIPTION
**Pull request by pwalczysko**
See https://github.com/ome/www.openmicroscopy.org/issues/348#issuecomment-740020699 for motivation

Adding OMERO to licensing page with the text suggested in https://github.com/ome/www.openmicroscopy.org/issues/348#issuecomment-740020699

cc @manics @joshmoore

### CODE REVIEW

**Comment by joshmoore** [comment]
Screen Shot 2020-12-08 at 10 55 50

**Comment by joshmoore** [comment]
I think this is a fine start. I imagine we could remove a bit of the redundancy by separating it down into licenses:

 - GPL
   - Bio-Formats
   - OMERO
 - BSD
   - Bio-Formats (BSD)
   - OME-Files

etc. but I don't propose to do that kind of overhaul here.

Any other thoughts, @sbesson @jburel @jrswedlow @chris-allan ?

**Comment by sbesson** [comment]
Agreed this might need reworking to express the granularity of the licensing between the different components of each product. I don't have an immediate suggestion so let's start with clarifying the OMERO expectations on the website as it stands and then coming back to this in a second step. Thanks @pwalczysko

**Comment by sbesson** [comment]
Now deployed at https://www.openmicroscopy.org/licensing/

**Pull request merged**
